version: '3.3'

services:

  django:
    build: .
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:14.3-alpine3.16
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django