version: '3.9'

services:

  django:
    build: .
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:14.3-alpine3.16
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./certbot/conf:/etc/letsencrypt    # Configuración de Certbot
      - ./certbot/www:/var/www/certbot     # Carpeta para validación

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"
